# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_fibercryptopy')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_fibercryptopy')
    _fibercryptopy = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fibercryptopy', [dirname(__file__)])
        except ImportError:
            import _fibercryptopy
            return _fibercryptopy
        try:
            _mod = imp.load_module('_fibercryptopy', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _fibercryptopy = swig_import_helper()
    del swig_import_helper
else:
    import _fibercryptopy
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def equalSlices(slice1: 'GoSlice', slice2: 'GoSlice', elem_size: 'int') -> "int":
    return _fibercryptopy.equalSlices(slice1, slice2, elem_size)
equalSlices = _fibercryptopy.equalSlices
class _GoString_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _GoString_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _GoString_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _fibercryptopy._GoString__p_set
    __swig_getmethods__["p"] = _fibercryptopy._GoString__p_get
    if _newclass:
        p = _swig_property(_fibercryptopy._GoString__p_get, _fibercryptopy._GoString__p_set)
    __swig_setmethods__["n"] = _fibercryptopy._GoString__n_set
    __swig_getmethods__["n"] = _fibercryptopy._GoString__n_get
    if _newclass:
        n = _swig_property(_fibercryptopy._GoString__n_get, _fibercryptopy._GoString__n_set)

    def __init__(self):
        this = _fibercryptopy.new__GoString_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete__GoString_
    __del__ = lambda self: None
_GoString__swigregister = _fibercryptopy._GoString__swigregister
_GoString__swigregister(_GoString_)

class GoInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoInterface, name)
    __repr__ = _swig_repr
    __swig_setmethods__["t"] = _fibercryptopy.GoInterface_t_set
    __swig_getmethods__["t"] = _fibercryptopy.GoInterface_t_get
    if _newclass:
        t = _swig_property(_fibercryptopy.GoInterface_t_get, _fibercryptopy.GoInterface_t_set)
    __swig_setmethods__["v"] = _fibercryptopy.GoInterface_v_set
    __swig_getmethods__["v"] = _fibercryptopy.GoInterface_v_get
    if _newclass:
        v = _swig_property(_fibercryptopy.GoInterface_v_get, _fibercryptopy.GoInterface_v_set)

    def __init__(self):
        this = _fibercryptopy.new_GoInterface()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoInterface
    __del__ = lambda self: None
GoInterface_swigregister = _fibercryptopy.GoInterface_swigregister
GoInterface_swigregister(GoInterface)

class GoSlice(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoSlice, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoSlice, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _fibercryptopy.GoSlice_data_set
    __swig_getmethods__["data"] = _fibercryptopy.GoSlice_data_get
    if _newclass:
        data = _swig_property(_fibercryptopy.GoSlice_data_get, _fibercryptopy.GoSlice_data_set)
    __swig_setmethods__["len"] = _fibercryptopy.GoSlice_len_set
    __swig_getmethods__["len"] = _fibercryptopy.GoSlice_len_get
    if _newclass:
        len = _swig_property(_fibercryptopy.GoSlice_len_get, _fibercryptopy.GoSlice_len_set)
    __swig_setmethods__["cap"] = _fibercryptopy.GoSlice_cap_set
    __swig_getmethods__["cap"] = _fibercryptopy.GoSlice_cap_get
    if _newclass:
        cap = _swig_property(_fibercryptopy.GoSlice_cap_get, _fibercryptopy.GoSlice_cap_set)

    def __init__(self):
        this = _fibercryptopy.new_GoSlice()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoSlice
    __del__ = lambda self: None
GoSlice_swigregister = _fibercryptopy.GoSlice_swigregister
GoSlice_swigregister(GoSlice)


def FC_util_AltcoinCaption(p0: '_GoString_') -> "GoString_ *":
    return _fibercryptopy.FC_util_AltcoinCaption(p0)
FC_util_AltcoinCaption = _fibercryptopy.FC_util_AltcoinCaption

def FC_handle_close(p0: 'Handle') -> "void":
    return _fibercryptopy.FC_handle_close(p0)
FC_handle_close = _fibercryptopy.FC_handle_close

def FC_util_Min(p0: 'GoInt', p1: 'GoInt') -> "GoInt *":
    return _fibercryptopy.FC_util_Min(p0, p1)
FC_util_Min = _fibercryptopy.FC_util_Min

def FC_util_GetCoinValue(p0: '_GoString_', p1: '_GoString_') -> "GoUint64 *":
    return _fibercryptopy.FC_util_GetCoinValue(p0, p1)
FC_util_GetCoinValue = _fibercryptopy.FC_util_GetCoinValue

def FC_util_FormatUint64(p0: 'GoUint64') -> "GoString_ *":
    return _fibercryptopy.FC_util_FormatUint64(p0)
FC_util_FormatUint64 = _fibercryptopy.FC_util_FormatUint64

def FC_util_FormatCoins(p0: 'GoUint64', p1: 'GoUint64') -> "GoString_ *":
    return _fibercryptopy.FC_util_FormatCoins(p0, p1)
FC_util_FormatCoins = _fibercryptopy.FC_util_FormatCoins

def FC_util_RemoveZeros(p0: '_GoString_') -> "GoString_ *":
    return _fibercryptopy.FC_util_RemoveZeros(p0)
FC_util_RemoveZeros = _fibercryptopy.FC_util_RemoveZeros

def FC_util_StringInList(p0: '_GoString_', p1: 'Strings__Handle') -> "GoUint8 *":
    return _fibercryptopy.FC_util_StringInList(p0, p1)
FC_util_StringInList = _fibercryptopy.FC_util_StringInList

def FC_JsonEncode_Handle(p0: 'Handle') -> "GoString_ *":
    return _fibercryptopy.FC_JsonEncode_Handle(p0)
FC_JsonEncode_Handle = _fibercryptopy.FC_JsonEncode_Handle
FC_OK = _fibercryptopy.FC_OK
FC_ERROR = _fibercryptopy.FC_ERROR
FC_BAD_HANDLE = _fibercryptopy.FC_BAD_HANDLE
FC_INVALID_TIMESTRING = _fibercryptopy.FC_INVALID_TIMESTRING
class GoComplex64_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoComplex64_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoComplex64_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["real"] = _fibercryptopy.GoComplex64__real_set
    __swig_getmethods__["real"] = _fibercryptopy.GoComplex64__real_get
    if _newclass:
        real = _swig_property(_fibercryptopy.GoComplex64__real_get, _fibercryptopy.GoComplex64__real_set)
    __swig_setmethods__["imaginary"] = _fibercryptopy.GoComplex64__imaginary_set
    __swig_getmethods__["imaginary"] = _fibercryptopy.GoComplex64__imaginary_get
    if _newclass:
        imaginary = _swig_property(_fibercryptopy.GoComplex64__imaginary_get, _fibercryptopy.GoComplex64__imaginary_set)

    def __init__(self):
        this = _fibercryptopy.new_GoComplex64_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoComplex64_
    __del__ = lambda self: None
GoComplex64__swigregister = _fibercryptopy.GoComplex64__swigregister
GoComplex64__swigregister(GoComplex64_)

class GoComplex128_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoComplex128_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoComplex128_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["real"] = _fibercryptopy.GoComplex128__real_set
    __swig_getmethods__["real"] = _fibercryptopy.GoComplex128__real_get
    if _newclass:
        real = _swig_property(_fibercryptopy.GoComplex128__real_get, _fibercryptopy.GoComplex128__real_set)
    __swig_setmethods__["imaginary"] = _fibercryptopy.GoComplex128__imaginary_set
    __swig_getmethods__["imaginary"] = _fibercryptopy.GoComplex128__imaginary_get
    if _newclass:
        imaginary = _swig_property(_fibercryptopy.GoComplex128__imaginary_get, _fibercryptopy.GoComplex128__imaginary_set)

    def __init__(self):
        this = _fibercryptopy.new_GoComplex128_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoComplex128_
    __del__ = lambda self: None
GoComplex128__swigregister = _fibercryptopy.GoComplex128__swigregister
GoComplex128__swigregister(GoComplex128_)

class GoString_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoString_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoString_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _fibercryptopy.GoString__p_set
    __swig_getmethods__["p"] = _fibercryptopy.GoString__p_get
    if _newclass:
        p = _swig_property(_fibercryptopy.GoString__p_get, _fibercryptopy.GoString__p_set)
    __swig_setmethods__["n"] = _fibercryptopy.GoString__n_set
    __swig_getmethods__["n"] = _fibercryptopy.GoString__n_get
    if _newclass:
        n = _swig_property(_fibercryptopy.GoString__n_get, _fibercryptopy.GoString__n_set)

    def __init__(self):
        this = _fibercryptopy.new_GoString_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoString_
    __del__ = lambda self: None
GoString__swigregister = _fibercryptopy.GoString__swigregister
GoString__swigregister(GoString_)

class GoInterface_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoInterface_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoInterface_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["t"] = _fibercryptopy.GoInterface__t_set
    __swig_getmethods__["t"] = _fibercryptopy.GoInterface__t_get
    if _newclass:
        t = _swig_property(_fibercryptopy.GoInterface__t_get, _fibercryptopy.GoInterface__t_set)
    __swig_setmethods__["v"] = _fibercryptopy.GoInterface__v_set
    __swig_getmethods__["v"] = _fibercryptopy.GoInterface__v_get
    if _newclass:
        v = _swig_property(_fibercryptopy.GoInterface__v_get, _fibercryptopy.GoInterface__v_set)

    def __init__(self):
        this = _fibercryptopy.new_GoInterface_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoInterface_
    __del__ = lambda self: None
GoInterface__swigregister = _fibercryptopy.GoInterface__swigregister
GoInterface__swigregister(GoInterface_)

class GoSlice_(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GoSlice_, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GoSlice_, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _fibercryptopy.GoSlice__data_set
    __swig_getmethods__["data"] = _fibercryptopy.GoSlice__data_get
    if _newclass:
        data = _swig_property(_fibercryptopy.GoSlice__data_get, _fibercryptopy.GoSlice__data_set)
    __swig_setmethods__["len"] = _fibercryptopy.GoSlice__len_set
    __swig_getmethods__["len"] = _fibercryptopy.GoSlice__len_get
    if _newclass:
        len = _swig_property(_fibercryptopy.GoSlice__len_get, _fibercryptopy.GoSlice__len_set)
    __swig_setmethods__["cap"] = _fibercryptopy.GoSlice__cap_set
    __swig_getmethods__["cap"] = _fibercryptopy.GoSlice__cap_get
    if _newclass:
        cap = _swig_property(_fibercryptopy.GoSlice__cap_get, _fibercryptopy.GoSlice__cap_set)

    def __init__(self):
        this = _fibercryptopy.new_GoSlice_()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibercryptopy.delete_GoSlice_
    __del__ = lambda self: None
GoSlice__swigregister = _fibercryptopy.GoSlice__swigregister
GoSlice__swigregister(GoSlice_)

# This file is compatible with both classic and new-style classes.


